-- In-app notifications for customer accounts.
-- Lease, maintenance and purchase-offer notices are generated by
-- src/services/lease_notifications.py for the appropriate customer accounts.
-- Lease/maintenance reminders use days; offer reminders use hours.
-- Run after supabase_accounts.sql and supabase_rental_applications.sql.

create table if not exists account_notifications (
  id                uuid primary key default gen_random_uuid(),
  account_id        uuid not null references accounts(id) on delete cascade,
  notification_type text not null,
  title             text not null,
  message           text not null,
  property_id       text references properties(id) on delete set null,
  reference_id      uuid,
  reference_date    date,
  reference_at      timestamptz,
  dedupe_key        text not null unique,
  recipient_role    text not null check (recipient_role in ('tenant', 'owner', 'investor')),
  read_at           timestamptz,
  created_at        timestamptz not null default now()
);


-- If account_notifications already existed from the earlier lease-only version,
-- widen its recipient-role constraint so investor offer alerts can use it too.
alter table account_notifications
  drop constraint if exists account_notifications_recipient_role_check;
alter table account_notifications
  add constraint account_notifications_recipient_role_check
  check (recipient_role in ('tenant', 'owner', 'investor'));

create index if not exists account_notifications_account_idx
  on account_notifications (account_id, read_at, created_at desc);
create index if not exists account_notifications_type_idx
  on account_notifications (notification_type, created_at desc);

alter table account_notifications enable row level security;
revoke all on account_notifications from anon, authenticated;

-- Safe upgrade for databases created with the first lease-only version.
alter table account_notifications add column if not exists reference_at timestamptz;
