"""PDF of a purchase offer a tenant and owner agreed on (tenant_offers).

Made once the owner presses "Approve tenant" on an accepted offer
(rentals.owner_decision). The tenant downloads it from their Portfolio tab,
the owner from their Tenants tab. Like purchase_offer_pdf.py it is a plain
summary of the agreed terms - not a purchase contract.
"""
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from src.services.purchase_offer_pdf import (
    BODY, H2, NOTICE, NOTICE_BG, SMALL, SUB, TITLE, grid, money, nice_date, nice_dt, txt,
)


def render(*, reference: str, property_info: dict, buyer: dict, seller: dict, terms: dict,
           accepted_at: str | None, approved_at: str | None, generated_at: str | None) -> bytes:
    currency = terms.get("currency") or "USD"
    buffer = BytesIO()

    def decorate(canvas, doc):
        canvas.saveState()
        width, _ = LETTER
        canvas.setFillColor(colors.HexColor("#777777"))
        canvas.setFont("Helvetica-Bold", 8.5)
        canvas.drawString(0.75 * inch, 0.5 * inch, f"{reference} · Accepted purchase offer")
        canvas.drawRightString(width - 0.75 * inch, 0.5 * inch, f"Page {doc.page}")
        canvas.restoreState()

    doc = SimpleDocTemplate(
        buffer, pagesize=LETTER, leftMargin=0.75 * inch, rightMargin=0.75 * inch,
        topMargin=0.7 * inch, bottomMargin=0.75 * inch,
        title=f"Accepted purchase offer - {reference}", author="Staybot", subject="Accepted purchase offer",
    )

    dd_days = terms.get("due_diligence_period_days")
    story = [
        Paragraph("Accepted purchase offer", TITLE),
        Paragraph(f"Reference {txt(reference)} · Generated {nice_dt(generated_at)}", SUB),
        Spacer(1, 8),
        Table([[Paragraph(
            "Both sides agreed on the terms below through Staybot and the owner approved them. This is a "
            "summary of the agreed offer - it is not a purchase contract. The contract itself is prepared "
            "and signed through the broker / attorney.",
            NOTICE,
        )]], colWidths=(6.5 * inch), style=TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), NOTICE_BG),
            ("BOX", (0, 0), (-1, -1), 0.7, colors.HexColor("#e4bf62")),
            ("LEFTPADDING", (0, 0), (-1, -1), 10), ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ("TOPPADDING", (0, 0), (-1, -1), 8), ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ])),
        Paragraph("Property", H2),
        grid([
            ("Home", txt(property_info.get("title"))),
            ("Address", txt(property_info.get("address"))),
            ("Listing reference", txt(property_info.get("id"))),
        ]),
        Paragraph("Buyer", H2),
        grid([
            ("Name", txt(buyer.get("name"))),
            ("Email", txt(buyer.get("email"))),
            ("Phone", txt(buyer.get("phone"))),
        ]),
        Paragraph("Owner", H2),
        grid([("Name", txt(seller.get("name")))]),
        Paragraph("Agreed terms", H2),
        grid([
            ("Offer price", money(terms.get("price"), currency)),
            ("Earnest money", money(terms.get("earnest_money"), currency)),
            ("Due diligence fee", money(terms.get("due_diligence_fee"), currency)),
            ("Due diligence period", txt(dd_days) + (" days" if dd_days is not None else "")),
            ("Due diligence ends", nice_date(terms.get("due_diligence_end"))),
            ("Financing deadline", nice_date(terms.get("financing_deadline"))),
            ("Financing contingency", txt(terms.get("financing_contingency"))),
            ("What is included", txt(terms.get("included"))),
            ("Closing date", nice_date(terms.get("closing_date"))),
        ]),
        Paragraph("Agreement", H2),
        grid([
            ("Offer accepted", nice_dt(accepted_at)),
            ("Approved by the owner", nice_dt(approved_at)),
        ]),
        Spacer(1, 10),
        Paragraph("Keep this document for your records. Questions about the terms? Message the owner from "
                  "the Messages tab in Staybot.", BODY),
        Spacer(1, 6),
        Paragraph("Generated by Staybot from the offer both sides accepted. Not an electronic signature.", SMALL),
    ]

    doc.build(story, onFirstPage=decorate, onLaterPages=decorate)
    return buffer.getvalue()
